INSERT INTO events ("image", "title", "date", "description") VALUES 
('https://artatix.co.id/img/event_banner/665ac148bceb7-ARTJOGEVENTBANNER01.png','ARTJOG 2024','2024-06-29','ARTJOG adalah peristiwa seni yang berperan sebagai ruang berbagi pengetahuan dan pengalaman estetika serta perkembangan seni terbaru. ARTJOG sebagai sebuah festival hadir melalui pameran seni rupa dan berbagai presentasi program seni dan edukasi yang terus menyuguhkan beragam tawaran pengalaman baru.'),
('https://img.inews.co.id/media/600/files/networks/2023/01/29/1fc43_pon-xxi.jpg', 'PON XXI Aceh-Sumut 2024', '2024-09-08', 'Acara ini merupakan Pekan Olahraga Nasional (PON) yang diselenggarakan di provinsi Aceh dan Sumatera Utara. Terdapat lebih dari 46 cabang olahraga yang dipertandingkan, menciptakan panggung kompetisi yang luas dan beragam'),
('https://borobudurmarathon.com/wp-content/uploads/2024/05/unlocking-potensial.jpg', 'Borobudur Marathon', '2024-12-01', 'Bank Jateng Borobudur Marathon 2024 akan diadakan pada 1 Desember 2024 di Magelang, Jawa Tengah. Acara ini menantang para pelari dari seluruh Indonesia dan luar negeri untuk menembus batas, menunjukkan determinasi, melengkapi perjalanan lari mereka, dan meninggalkan jejak serta legacy di Borobudur Marathon.'),
('https://artatix.co.id/img/event_banner/66ace454bbcf7-stry.jpeg', 'Story Indramayu Fest Vol 2', '2024-08-19', 'Story Indramayu vol 2 merupakan event lanjutan setelah tgl 10 juli kemarin pecaah dan lancar.Berdasarkan banyak nya Permintaan event lagi di indmryu dan animo ambyar yang luar baisa'),
('https://hariane.com/file/IMG_20230812_160349.jpg', 'Karnaval pembangunan Kabupaten Cilacap', '2024-08-22', 'Salah satu kabupaten yang juga ikut serta dalam memeriahkan HUT RI ini adalah Kabupaten Cilacap, yang akan menggelar acara karnaval dalam waktu dekat ini Biasanya acara karnaval yang dilangsungkan akan dimeriahkan oleh beberapa orang yang mengenakan kostum unik dan heboh sehingga menjadi pusat perhatian masyarakat.Salah satu kabupaten atau kota yang juga ikut berpartisipasi adalah Kabupaten Cilacap, Jawa Tengah.'),
('https://resources.motogp.pulselive.com/photo-resources/2024/06/14/3cd44f18-4739-4916-a401-347e1b2aa401/INA.jpg?height=465&width=1440', 'Pertamina Grand Prix of Indonesia', '2024-09-27', 'MotoGP di Sirkuit Mandalika adalah salah satu balapan paling dinantikan di kalender MotoGP. Sirkuit Mandalika, yang terletak di Mandalika, Lombok, Indonesia, adalah sirkuit jalan raya yang indah dengan pemandangan laut dan pegunungan yang spektakuler.'),
('https://colorrunfestival.id/images/event/VID000029.png', 'MAKASSAR COLOR RUN LIGHTFEST 2025', '2025-03-16', 'MAKASSAR COLOR RUN LIGHTFEST 2025 adalah sebuah acara lari yang dipadukan dengan festival cahaya dan warna, menawarkan pengalaman yang unik dan penuh keceriaan bagi para peserta. Acara ini diadakan di kota Makassar, Sulawesi Selatan, dan menjadi salah satu event tahunan yang paling dinanti oleh warga setempat dan wisatawan.'),
('https://artatix.co.id/img/event_banner/6686dfd9a65e1-YES1.png', 'Agricultural Day Competition 2024', '2024-07-05', 'Agricultural Day Competition (AGRIDATION) merupakan kegiatan perlombaan dan festival pada tingkat nasional di bidang pertanian, lingkungan, kesehatan, keuangan, dan teknologi yang bertujuan untuk mempromosikan pertanian di Indonesia. Kegiatan ini diselenggarakan oleh Lima Himpunan Mahasiswa Vokasi IPB. Acara puncak Agridation akan dimeriahkan dengan konser.'),
('https://artatix.co.id/img/event_banner/6689ec01a7903-lanternfest.png', 'Lanterne Festival De Paris 2024', '2024-09-07', 'Lanterne Festival De Paris (LF de Paris) adalah event budaya dan wisata kreatif dan event romantik yang merupakan produk brand NITE LANTERN FESTIVAL sebagai ajang promosi untuk lebih memperkenalkan Kawasan Wisata Pantai Parangtritis yang menjadi salah satu objek wisata andalan Kabupaten Bantul. LF de Paris merupakan Festival 1001 Lampion yang diterbangkan menghiasi langit malam, membuat suasana yang “instagramable” sehingga sangat menarik bagi semua kalangan yang ingin mengabadikan momen romantis bersama pasangan, atau antar sahabat yang ingin menerbangkan harapan setinggi-tingginya dengan lampion bertuliskan harapan sebagai simbol.'),
('https://artatix.co.id/img/event_banner/66a723c09f4a8-IMG_20240729_120802.jpg', 'INTIMATE CONCERT ANNIVERSARY SEWINDU BERSAMA FEBY PUTRI', '2024-08-31', 'Mari kita sama-sama ramaikan acara Febyours Intimate Concert Anniversary. Merupakan sebuah acara untuk memperingati terbentuknya Febyours yang ke-8 tahun. Acara ini akan menjadi sebuah momen spesial untuk merayakan pencapaian, kerja keras, dan dedikasi semua pihak dalam perjalanan panjang karir Feby Putri.');
